# Generated by Django 3.1.2 on 2020-11-06 01:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('desarrollador', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JuegoInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_lan', models.DateField(blank=True, null=True)),
                ('juego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.juego')),
            ],
        ),
    ]
