# Generated by Django 3.1.2 on 2020-11-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='titulo',
            new_name='title',
        ),
    ]
